In [2]:
import numpy as np

# Simulating coin flips

In [12]:
# outcome of on coin flip
np.random.randint(2)

0

In [4]:
# outcomes of ten thousand coin flips
np.random.randint(2, size=10000)

array([1, 0, 0, ..., 1, 1, 1])

In [5]:
# mean outcome of ten thousand coin flips
np.random.randint(2, size=10000).mean()

0.5058

In [6]:
# outcome of on coin flip
np.random.choice([0,1])

0

In [7]:
# outcome of ten thousand coin flips
np.random.choice([0,1], size=10000)

array([1, 1, 0, ..., 0, 1, 1])

In [9]:
# mean outcome of ten thousand coin flips
np.random.choice([0,1], size=10000).mean()

0.5045

In [10]:
# outcomes of ten thousand biased coin flips
np.random.choice([0,1], size=10000, p=[0.8, 0.2])

array([0, 1, 0, ..., 1, 0, 0])

In [11]:
# mean outcome of ten thousand biased coin flips
np.random.choice([0,1], size=10000, p=[0.8, 0.2]).mean()

0.1961

# Quiz

## 1. Two fair coin flips produce exactly two heads

In [15]:
# simulate 1 million tests of two fair coin flips
tests = np.random.randint(2, size=(int(1e6), 2))

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly two heads
(test_sums == 0).mean()

0.250047

## 2. Three fair coin flips produce exactly one head

In [17]:
# simulate 1 million tests of three fair coin flips
tests2 = np.random.randint(2, size=(int(1e6), 3))

# sums of all tests
test_sums = tests2.sum(axis=1)

# proportion of tests that produced exactly two heads
(test_sums==1).mean()

0.375006

## 3. Three biased coin flips with P(H) = 0.6 produce exactly one head

In [18]:
# simulate 1 million tests of three bias coin flips
# hint: use np.random.choice()
tests3 = np.random.choice([0,1], size=(int(1e6), 3), p=[0.6, 0.4])

#sums of all tests
test_sums = tests3.sum(axis=1)

# proportion of tests that produced exactly two heads
(test_sums==1).mean()

0.431572

## 4. A die rolls an even number
