<a href="https://colab.research.google.com/github/geocarvalho/python-ds/blob/master/MLmastering/linear_algebra_for_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [Basics for linear algebra for ML - Discover the mathematical language of data in python - Jason Bownlee](https://machinelearningmastery.com/linear_algebra_for_machine_learning/)

## Chapter 4 - Introduction to Numpy arrays

In [0]:
import numpy as np

# Create array
l = [1.0, 2.0, 3.0]
a = np.array(l)

# Display array
print(a)

# Display array shape
print(a.shape)

# Display array data type
print(a.dtype)

[1. 2. 3.]
(3,)
float64


### Creating arrays

* An empty array with aleatory numbers with `empty()`;
* An array with zeros using `zeros()`;
* An array with ones using `ones()`

In [0]:
# Create empty array
a = np.empty([3,3])
print(a)

[[3.18066103e-316 2.07507571e-322 2.12199579e-314]
 [3.44620186e-085 4.34900767e+199 1.87422380e+261]
 [1.43622020e+161 3.27748089e+180 1.27014396e-319]]


In [0]:
# Create zero array
a = np.zeros([3, 5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [0]:
# Create one array
a = np.ones([2,5])
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Combining arrays

* Vertical Stack with `vstack()`
* Horizontal Stack with `hstack()`

In [0]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(a1)
print(a2)

[1 2 3]
[4 5 6]


In [0]:
a3 = np.vstack((a1, a2))
print(a3)
print(a3.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [0]:
a4 = np.hstack((a1, a2))
print(a4)
print(a4.shape)

[1 2 3 4 5 6]
(6,)


## Chapter 5 - Index, slice and reshape Numpy arrays

### From list to arrays

* One-dimensional list to array
* Two-dimensional list of lists to array

In [0]:
# Create one-dimensional array
data1 = [11, 22, 33, 44, 55]

# Array of data
data1 = np.array(data1)
data1

array([11, 22, 33, 44, 55])

In [0]:
# Create two-dimensional array
data2 = [[11, 22],
        [33, 44],
        [55, 66]]

# Array of data
data2 = np.array(data2)
data2

array([[11, 22],
       [33, 44],
       [55, 66]])

### Array indexing
* One-dimensional indexing
* Two-dimensional indexing

In [0]:
# One-dimensional
print(data1[0])
print(data1[-1])

11
55


In [0]:
# Two dimensional
print(data2[0,0])
print(data2[0,])

11
[11 22]


In [0]:
# Two dimensional like C-based languages
print(data2[0])
print(data2[0][0])

[11 22]
11


### Array slicing
* One-dimensional slicing
* Two-dimensional slicing

In [0]:
# One-dimensional
print(data1[:])
print(data1[0:1])
print(data1[-2:])

[11 22 33 44 55]
[11]
[44 55]


In [0]:
# Two-dimensional
print(data2[:, :-1])
print(data2[:, -1])

[[11]
 [33]
 [55]]
[22 44 66]


In [0]:
data = np.array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])

print(data[:, :-1])
print(data[:, -1])

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


### Array reshaping
* Reshape 1d to 2d array

In [0]:
data1.shape

(5,)

In [0]:
data2.shape

(3, 2)

In [0]:
print( ' Rows: %d ' % data2.shape[0])
print( ' Cols: %d ' % data2.shape[1])

 Rows: 3 
 Cols: 2 


In [0]:
# reshape 1D to 2D array
data = data1.reshape((data1.shape[0], 1))
data.shape

(5, 1)

In [0]:
data = data2.reshape((data2.shape[0], data2.shape[1], 1))
print(data)
print(data.shape)

[[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]]
(3, 2, 1)


## Chapter 6 - Numpy array broadcasting

* Duplicate the smaller array so that it has the dimensionality and size as the larger array.

### Limitation with array arithmetic


In [0]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
c = a + b
c

array([2, 4, 6])

### Broadcast scalar to one-dimensional array


In [0]:
a = np.array([1, 2, 3])
b = 2
c = a + b
c

array([3, 4, 5])

### Broadcast scalar to two-dimensional array

In [0]:
a = np.array([
[1, 2, 3],
[1, 2, 3]])
b = 2
c = a + b
c

array([[3, 4, 5],
       [3, 4, 5]])

### One-dimensional and two-dimensional arrays

In [0]:
a = np.array([
[1, 2, 3],
[1, 2, 3]])
b = np.array([1,2,3])
c = a + b
c

array([[2, 4, 6],
       [2, 4, 6]])

### Limitations

* Arithmetic, including broadcasting, can only be performed when the shape of each dimension in the arrays are equal or one has the dimension size of 1.

In [0]:
a = np.array([
[1, 2, 3],
[1, 2, 3]])
print(a.shape)
b = np.array([1,2])
print(b.shape)
c = a + b
print(c)

(2, 3)
(2,)


ValueError: ignored

## Chapter 7 - Vectors and vector arithmetic

* Vector is a tuple of one or more values called scalars

In [0]:
v = np.array([1,2,3])
v

array([1, 2, 3])

In [0]:
a = np.array([1,2,3])
b = np.array([1,2,3])
c = a + b
c

array([2, 4, 6])

In [0]:
d = a - b
d

array([0, 0, 0])

In [0]:
e = a * b
e

array([1, 4, 9])

In [0]:
f = a / b
f

array([1., 1., 1.])

### Vector dot product

* The sum of the multiplied elements of two vectors of the same length.

In [0]:
g = a.dot(b)
g

14

### Vector-scalar multiplication

* Multiply each element of the vector by a scalar, resulting in a new scaled vector of the same length

In [0]:
s = 0.5
s * a

array([0.5, 1. , 1.5])

## Chapter 8 - Vector Norms

* Vector norm is the calculation of vector lengths or magnitudes;

* $L^1$ norm is the sum of the absolute values of the vector;

* $L^2$ norm is the square root of the sum of the squared vector values;

* The $max$ norm is the maximum vector values.


### Vector norm (magnitude)

* The length of the vector is always a positive number, except for a vector of zeros as values;

* It's calculated using some measure that summarizes the distance of the vector from the origin of the vector space.

### Vector $L¹$ norm

* The notation of a vector is $||v||_1$, where 1 is a subcript;

* This length is sometimes called **the taxicab norm** or **the Manhattan norm**;

$L^1(v) = ||v||_1$

* It's calculated as the sum of the absolute vector values, where the absolute value of a scalar uses the notation $|a_1|$;

* The norm is a calculation of the Manhattan distance from the origin of the vector space

$||v||_1 = |a_1| + |a_2| + |a_3|$

* It can be calculated in Numpy using the `norm()` function with a paramater to specify the norm order (1 in this case)



In [0]:
a = np.array([1, 2, 3])
l1 = np.linalg.norm(a, 1)
l1

6.0

> The $L^1$ norm is often used when fitting ML algorithms as a regularization method. For example, a method to keep the coefficients of the model small and in turn, the model less complex.

### Vector $L^2$ norm

* The notation is $||v||_2$, where 2 is a subscript

$L^2(v) = ||v||_2$

* It calculates the distance of the vector coordinate from the origin of the vector space. Also know as **the Euclidean norm** as it's calculated as the Euclidean distance from the origin;

* It's calculated as the square root of the sum of the squared vector values;

$||v||_2 = \sqrt{a^2_1 + a^2_2 + a^2_3}$

* It can be calculated in Numpy using the `norm()` function with default parameters;

In [0]:
l2 = np.linalg.norm(a)
l2

3.7416573867739413

> Like $L^1$ norm, $L^2$ norm is often used when fitting ML algorithms as a regularization method, but is more commonly used than other vector norms in ML. For example, a method to keep the coefficients of the model small and, in turn, the model less complex.

### Vector Max norm

* Referred as $L^{inf}$, the notation is $||v||_{inf}$;

$L^{inf}(v) = ||v||_{inf}$

* It's calculated as returning the maximum value of the vector;

$||v||_{inf} = \mathrm{max}a_1,a_2,a_3$

* It can be calculated in Numpy using the `norm()` function with the order parameter set to `inf`.

In [0]:
from math import inf

maxnorm = np.linalg.norm(a, inf)
maxnorm

3.0

> Max norm is also used as a regularization in ML, such as on NN weights, called max norm regularization.

---

## Chapter 9 - Matrices and matrix arithmetic

* Matrix is a two-dimensional array (a table) of numbers;

* The notation is often an uppercase letter, such as $A$, and entries are referred to by their two-dimensional subscript of row ($i$) and column ($j$), such as $a_{i,j}$;

$A = ((a_{1,1},a_{1,2}),(a_{2,1},a_{2,2}),(a_{3,1},a_{3,2}))$

* Often the dimensions of the matrix are denoted as $m$ and $n$ or $m \times n$ for the number of rows and the number of columns respectively.

### Defining a matrix

* In python we can represent a matrix using a two-dimensional Numpy array.


In [0]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

### Matrix arithmetic

* Some operations are performed element-wise between two matrices of equal size to result in a new matrix with the same size.

In [0]:
# Define first matrix
A = np.array([[1, 2, 3],
              [4, 5, 6]])
print(A)
# Define second matrix
B = np.array([[0.5, 0.5, 0.5],
              [0.5, 0.5, 0.5]])
print(B)


[[1 2 3]
 [4 5 6]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]


In [0]:
# Matrix addition
C = A + B
print(C)

[[1.5 2.5 3.5]
 [4.5 5.5 6.5]]


In [0]:
# Matrix subtraction
D = A - B
print(D)

[[0.5 1.5 2.5]
 [3.5 4.5 5.5]]


In [0]:
# Matrix multiplication (Hadamard product)
E = A * B
print(E)

[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [0]:
# Matrix division
F = A / B
print(F)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]


In [0]:
# Matrix-matrix multiplication (matrix dot)

* In matrix-matrix multiplication, the number of columns ($n$) in the first matrix ($A$) must be equal the number of rows ($m$) in the second matrix ($B$)

$C(m,k) = A(m,n) \cdot B(n,k)$

* The matrix multiplication using matrix notation

$ A = \begin{pmatrix}
       a_{1,1} & a_{1,2} \\[0.3em]
       a_{2,1} & a_{2,2} \\[0.3em]
       a_{3,1} & a_{3,2} \end{pmatrix}$

$ B = \begin{pmatrix}
       b_{1,1} & b_{1,2} \\[0.3em]
       b_{2,1} & b_{2,2} \end{pmatrix}$

$ C = \begin{pmatrix}
       a_{1,1} \times b_{1,1} + a_{1,2} \times b_{2,1},a_{1,1} \times b_{1,2} + a_{1,2} \times b_{2,2} \\
       a_{2,1} \times b_{1,1} + a_{2,2} \times b_{2,1},a_{2,1} \times b_{1,2} + a_{2,2} \times b_{2,2} \\
       a_{3,1} \times b_{1,1} + a_{3,2} \times b_{2,1},a_{3,1} \times b_{1,2} + a_{3,2} \times b_{2,2} \\ \end{pmatrix}$
       
       

* It can be implemented in Numpy using the `dot()` function or with the `@` in python3.5.

In [0]:
# define first matrix
A = np.array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# define second matrix
B = np.array([
[1, 2],
[3, 4]])
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]


In [0]:
# multiply matrices
C = A.dot(B)
print(C)
# multiply matrices with @ operator
D = A @ B
print(D)

[[ 7 10]
 [15 22]
 [23 34]]
[[ 7 10]
 [15 22]
 [23 34]]


### Matrix-vector multiplication

* The number of columns in the matrix must be equal the number of items in the vector;

* Because the vector only has one column, the result is always a vector;

$c = A \cdot v$

$ A = \begin{pmatrix}
       a_{1,1} & a_{1,2} \\[0.3em]
       a_{2,1} & a_{2,2} \\[0.3em]
       a_{3,1} & a_{3,2} \end{pmatrix}$

$ v = \begin{pmatrix}
       v_1 \\[0.3em]
       v_2 \end{pmatrix}$

$ c = \begin{pmatrix}
       a_{1,1} \times v_1 + a_{1,2} \times v_2 \\
       a_{2,1} \times v_1 + a_{2,2} \times v_2 \\
       a_{3,1} \times v_1 + a_{3,2} \times v_2 \\ \end{pmatrix}$
       

In [0]:
# matrix-vector multiplication
A = np.array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# define vector
B = np.array([0.5, 0.5])
print(B)
# multiply
C = A.dot(B)
print(C)

[[1 2]
 [3 4]
 [5 6]]
[0.5 0.5]
[1.5 3.5 5.5]


### Matrix-scalar multiplication

$C = A \cdot b$

$ A = \begin{pmatrix}
       a_{1,1} & a_{1,2} \\[0.3em]
       a_{2,1} & a_{2,2} \\[0.3em]
       a_{3,1} & a_{3,2} \end{pmatrix}$

$ c = \begin{pmatrix}
       a_{1,1} \times b+ a_{1,2} \times b \\
       a_{2,1} \times b + a_{2,2} \times b \\
       a_{3,1} \times b + a_{3,2} \times b \\ \end{pmatrix}$

In [0]:
# matrix-scalar multiplication
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)
# define scalar
b = 0.5
print(b)
# multiply
C = A * b
print(C)

[[1 2]
 [3 4]
 [5 6]]
0.5
[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


## Chapter 10 - Types of matrices