<a href="https://colab.research.google.com/github/geocarvalho/python-ds/blob/master/sentdex/nnfs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Neural networks from scratch

* [Book](https://nnfs.io/)
* [Video - Neural Networks from Scratch - P.1 Intro and Neuron Code
](https://www.youtube.com/watch?v=Wo5dMEP_BbI)

In [0]:
import sys
import numpy as np
import matplotlib

print("Python: ", sys.version)
print("Numpy: ", np.__version__)
print("Mapltolib: ", matplotlib.__version__)

Python:  3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
Numpy:  1.18.3
Mapltolib:  3.2.1


In [0]:
inputs = [1.2, 5.1, 2.1]
weights = [3.1, 2.1, 8.7]
bias = 3

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias 
print(output)

35.7


## [Neural Networks from Scratch - P.2 Coding a Layer](https://www.youtube.com/watch?v=lGLto9Xd7bU)


In [0]:
inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]
bias = 2

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias 
print(output)

2.3


* Estamos estudando apenas um neuronio, por isso ele só possui um *bias*;

* Estamos vendo a camada de *input* (*input layer*) ou poderia ser o *output* de neurônios anteriores;

* Vamos adicionar mais um *input*, como se fosse uma camada para 3 neurônios:

In [0]:
inputs = [1, 2, 3, 2.5]

weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + \
          inputs[3]*weights1[3] + bias1,
          inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + \
          inputs[3]*weights2[3] + bias2,
          inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + \
          inputs[3]*weights3[3] + bias3] 
print(output)

[4.8, 1.21, 2.385]


## [Neural Networks from Scratch - P.3 The Dot Product](https://www.youtube.com/watch?v=tMrbN67U9d4)

* [github](https://github.com/Sentdex/NNfSiX)

In [0]:
inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

layer_outputs = [] # Output of current layer
for neuron_weights, neuron_bias in zip(weights, biases):
  neuron_output = 0 # Output of given neuron
  for n_input, weight in zip(inputs, neuron_weights):
    neuron_output += n_input * weight
  neuron_output += neuron_bias
  layer_outputs.append(neuron_output)

print(layer_outputs)


[4.8, 1.21, 2.385]


* Tensors can be represented in arrays;
* We have to use *dot product*:


In [0]:
a = [1, 2, 3]
b = [2, 3, 4]
dot_product = a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
dot_product


20

In [0]:
inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2

output = np.dot(weights, inputs) + bias
output

4.8

* The first element in `np.dot()` is important because it's how the output format will come.

In [0]:
inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

output = np.dot(weights, inputs) + biases
output

array([4.8  , 1.21 , 2.385])

## [Neural Networks from Scratch - P.4 Batches, Layers, and Objects](https://www.youtube.com/watch?v=TEWy9vZcxW4)

* We gonna add more inputs (sample1, sample2, sample3), and to the dot product work we need to transpose the matrix;

* We need to multiple the sample1 by the neuron1, for this we need to pass the inputs and the weights matrix transposed;

> $line \cdot column$

In [0]:
# Sample1, sample2, sample3
inputs = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

# Neuron1, neuron2, neuron3
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

output = np.dot(inputs, np.array(weights).T) + biases
output

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

* Now we'll add a new layer of neurons

In [0]:
# Sample1, sample2, sample3
inputs = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

# Layer1 = Neuron1, neuron2, neuron3
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

# Layer2 = Neuron1, neuron2, neuron3
weights2 = [[0.1, -0.14, 0.5],
           [-0.5, 0.12, -0.33],
           [-0.44, 0.73, -0.13]]
biases2 = [-1, 2, -0.5]

layer1_outputs = np.dot(inputs, np.array(weights).T) + biases
layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2
print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


* Let's transform everything in objects;

* Normalize the input between -1 and +1, and the biases as 0s;

In [0]:
np.random.seed(0)

# Sample1, sample2, sample3
X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1, n_neurons))
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X)
print(layer1.output)
print()
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]

[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]
